# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mike.levine\Desktop\tmp\SalmonCollection.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_salmoncollectionDlg(object):
    def setupUi(self, salmoncollectionDlg):
        salmoncollectionDlg.setObjectName(_fromUtf8("salmoncollectionDlg"))
        salmoncollectionDlg.resize(880, 597)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(salmoncollectionDlg.sizePolicy().hasHeightForWidth())
        salmoncollectionDlg.setSizePolicy(sizePolicy)
        salmoncollectionDlg.setMinimumSize(QtCore.QSize(200, 0))
        self.gridLayout_2 = QtGui.QGridLayout(salmoncollectionDlg)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(salmoncollectionDlg)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(salmoncollectionDlg)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Btn4 = QtGui.QPushButton(self.groupBox)
        self.Btn4.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn4.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn4.setFont(font)
        self.Btn4.setText(_fromUtf8(""))
        self.Btn4.setCheckable(True)
        self.Btn4.setObjectName(_fromUtf8("Btn4"))
        self.gridLayout.addWidget(self.Btn4, 0, 4, 1, 1)
        self.clearBtn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearBtn.sizePolicy().hasHeightForWidth())
        self.clearBtn.setSizePolicy(sizePolicy)
        self.clearBtn.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName(_fromUtf8("clearBtn"))
        self.gridLayout.addWidget(self.clearBtn, 4, 0, 1, 1)
        self.Btn7 = QtGui.QPushButton(self.groupBox)
        self.Btn7.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn7.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn7.setFont(font)
        self.Btn7.setText(_fromUtf8(""))
        self.Btn7.setCheckable(True)
        self.Btn7.setObjectName(_fromUtf8("Btn7"))
        self.gridLayout.addWidget(self.Btn7, 2, 2, 1, 1)
        self.Btn6 = QtGui.QPushButton(self.groupBox)
        self.Btn6.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn6.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn6.setFont(font)
        self.Btn6.setText(_fromUtf8(""))
        self.Btn6.setCheckable(True)
        self.Btn6.setObjectName(_fromUtf8("Btn6"))
        self.gridLayout.addWidget(self.Btn6, 2, 1, 1, 1)
        self.Btn5 = QtGui.QPushButton(self.groupBox)
        self.Btn5.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn5.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn5.setFont(font)
        self.Btn5.setText(_fromUtf8(""))
        self.Btn5.setCheckable(True)
        self.Btn5.setObjectName(_fromUtf8("Btn5"))
        self.gridLayout.addWidget(self.Btn5, 2, 0, 1, 1)
        self.doneBtn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneBtn.sizePolicy().hasHeightForWidth())
        self.doneBtn.setSizePolicy(sizePolicy)
        self.doneBtn.setMinimumSize(QtCore.QSize(200, 200))
        self.doneBtn.setMaximumSize(QtCore.QSize(1667775, 1667775))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName(_fromUtf8("doneBtn"))
        self.gridLayout.addWidget(self.doneBtn, 4, 4, 1, 1)
        self.Btn3 = QtGui.QPushButton(self.groupBox)
        self.Btn3.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn3.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn3.setFont(font)
        self.Btn3.setText(_fromUtf8(""))
        self.Btn3.setCheckable(True)
        self.Btn3.setObjectName(_fromUtf8("Btn3"))
        self.gridLayout.addWidget(self.Btn3, 0, 2, 1, 1)
        self.Btn2 = QtGui.QPushButton(self.groupBox)
        self.Btn2.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn2.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn2.setFont(font)
        self.Btn2.setText(_fromUtf8(""))
        self.Btn2.setCheckable(True)
        self.Btn2.setObjectName(_fromUtf8("Btn2"))
        self.gridLayout.addWidget(self.Btn2, 0, 1, 1, 1)
        self.Btn1 = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn1.sizePolicy().hasHeightForWidth())
        self.Btn1.setSizePolicy(sizePolicy)
        self.Btn1.setMinimumSize(QtCore.QSize(200, 100))
        self.Btn1.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Btn1.setFont(font)
        self.Btn1.setText(_fromUtf8(""))
        self.Btn1.setCheckable(True)
        self.Btn1.setObjectName(_fromUtf8("Btn1"))
        self.gridLayout.addWidget(self.Btn1, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(salmoncollectionDlg)
        QtCore.QMetaObject.connectSlotsByName(salmoncollectionDlg)

    def retranslateUi(self, salmoncollectionDlg):
        salmoncollectionDlg.setWindowTitle(_translate("salmoncollectionDlg", "Special Studies", None))
        self.label_3.setText(_translate("salmoncollectionDlg", "Missing fins?", None))
        self.clearBtn.setText(_translate("salmoncollectionDlg", "Clear", None))
        self.doneBtn.setText(_translate("salmoncollectionDlg", "Done", None))

