# Form implementation generated from reading ui file 'C:\Users\Melina.Shak\Documents\CLAMS\ui\SexSelDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_sexselDlg(object):
    def setupUi(self, sexselDlg):
        sexselDlg.setObjectName("sexselDlg")
        sexselDlg.resize(233, 209)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(sexselDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=sexselDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.maleBtn = QtWidgets.QPushButton(parent=sexselDlg)
        self.maleBtn.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maleBtn.setFont(font)
        self.maleBtn.setObjectName("maleBtn")
        self.verticalLayout.addWidget(self.maleBtn)
        self.femaleBtn = QtWidgets.QPushButton(parent=sexselDlg)
        self.femaleBtn.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.femaleBtn.setFont(font)
        self.femaleBtn.setObjectName("femaleBtn")
        self.verticalLayout.addWidget(self.femaleBtn)
        self.noneBtn = QtWidgets.QPushButton(parent=sexselDlg)
        self.noneBtn.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.noneBtn.setFont(font)
        self.noneBtn.setObjectName("noneBtn")
        self.verticalLayout.addWidget(self.noneBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(sexselDlg)
        QtCore.QMetaObject.connectSlotsByName(sexselDlg)

    def retranslateUi(self, sexselDlg):
        _translate = QtCore.QCoreApplication.translate
        sexselDlg.setWindowTitle(_translate("sexselDlg", "Sex Selection"))
        self.label.setText(_translate("sexselDlg", "Select the sex..."))
        self.maleBtn.setText(_translate("sexselDlg", "Male"))
        self.femaleBtn.setText(_translate("sexselDlg", "Female"))
        self.noneBtn.setText(_translate("sexselDlg", "Unsexed"))
