# Form implementation generated from reading ui file 'C:\Users\Melina.Shak\Documents\CLAMS\ui\SpecimenDelDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_specimendelDlg(object):
    def setupUi(self, specimendelDlg):
        specimendelDlg.setObjectName("specimendelDlg")
        specimendelDlg.resize(660, 403)
        self.verticalLayout = QtWidgets.QVBoxLayout(specimendelDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.delBtn = QtWidgets.QPushButton(parent=specimendelDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delBtn.setFont(font)
        self.delBtn.setObjectName("delBtn")
        self.gridLayout.addWidget(self.delBtn, 2, 0, 1, 1)
        self.delSpecimen = QtWidgets.QTableWidget(parent=specimendelDlg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.delSpecimen.setFont(font)
        self.delSpecimen.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectColumns)
        self.delSpecimen.setObjectName("delSpecimen")
        self.delSpecimen.setColumnCount(0)
        self.delSpecimen.setRowCount(0)
        self.gridLayout.addWidget(self.delSpecimen, 1, 0, 1, 3)
        self.okBtn = QtWidgets.QPushButton(parent=specimendelDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.gridLayout.addWidget(self.okBtn, 2, 2, 1, 1)
        self.cancelBtn = QtWidgets.QPushButton(parent=specimendelDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout.addWidget(self.cancelBtn, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=specimendelDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label.raise_()

        self.retranslateUi(specimendelDlg)
        QtCore.QMetaObject.connectSlotsByName(specimendelDlg)

    def retranslateUi(self, specimendelDlg):
        _translate = QtCore.QCoreApplication.translate
        specimendelDlg.setWindowTitle(_translate("specimendelDlg", "Delete Specimen"))
        self.delBtn.setText(_translate("specimendelDlg", "Delete"))
        self.okBtn.setText(_translate("specimendelDlg", "Done"))
        self.cancelBtn.setText(_translate("specimendelDlg", "Cancel"))
        self.label.setText(_translate("specimendelDlg", "Select measurement to delete"))
