# Form implementation generated from reading ui file 'C:\Users\Melina.Shak\Documents\CLAMS\ui\ScaleCardDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_scalecardDlg(object):
    def setupUi(self, scalecardDlg):
        scalecardDlg.setObjectName("scalecardDlg")
        scalecardDlg.resize(287, 320)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(scalecardDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=scalecardDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(parent=scalecardDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cardBtn = QtWidgets.QPushButton(parent=scalecardDlg)
        self.cardBtn.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cardBtn.setFont(font)
        self.cardBtn.setObjectName("cardBtn")
        self.verticalLayout.addWidget(self.cardBtn)
        self.label_2 = QtWidgets.QLabel(parent=scalecardDlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.positionBtn = QtWidgets.QPushButton(parent=scalecardDlg)
        self.positionBtn.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.positionBtn.setFont(font)
        self.positionBtn.setObjectName("positionBtn")
        self.verticalLayout.addWidget(self.positionBtn)
        self.doneBtn = QtWidgets.QPushButton(parent=scalecardDlg)
        self.doneBtn.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.verticalLayout.addWidget(self.doneBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.cardBtn.raise_()
        self.label.raise_()

        self.retranslateUi(scalecardDlg)
        QtCore.QMetaObject.connectSlotsByName(scalecardDlg)

    def retranslateUi(self, scalecardDlg):
        _translate = QtCore.QCoreApplication.translate
        scalecardDlg.setWindowTitle(_translate("scalecardDlg", "Scale Location"))
        self.label_3.setText(_translate("scalecardDlg", "Fish Scale Location"))
        self.label.setText(_translate("scalecardDlg", "Card Number"))
        self.cardBtn.setText(_translate("scalecardDlg", "enter"))
        self.label_2.setText(_translate("scalecardDlg", "Card Position"))
        self.positionBtn.setText(_translate("scalecardDlg", "enter"))
        self.doneBtn.setText(_translate("scalecardDlg", "Done"))
