# Form implementation generated from reading ui file 'C:\Users\Melina.Shak\Documents\CLAMS\ui\TimeDlg.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_timeDlg(object):
    def setupUi(self, timeDlg):
        timeDlg.setObjectName("timeDlg")
        timeDlg.resize(379, 323)
        self.verticalLayout = QtWidgets.QVBoxLayout(timeDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=timeDlg)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.dateEdit = QtWidgets.QDateEdit(parent=timeDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateEdit)
        self.timeEdit = QtWidgets.QTimeEdit(parent=timeDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeEdit.setFont(font)
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.timeEdit)
        self.pbGetCurrentTime = QtWidgets.QPushButton(parent=timeDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pbGetCurrentTime.setFont(font)
        self.pbGetCurrentTime.setObjectName("pbGetCurrentTime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pbGetCurrentTime)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelBtn = QtWidgets.QPushButton(parent=timeDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.okBtn = QtWidgets.QPushButton(parent=timeDlg)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.okBtn.setFont(font)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout.addWidget(self.okBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(timeDlg)
        QtCore.QMetaObject.connectSlotsByName(timeDlg)

    def retranslateUi(self, timeDlg):
        _translate = QtCore.QCoreApplication.translate
        timeDlg.setWindowTitle(_translate("timeDlg", "Edit Event Time"))
        self.label.setText(_translate("timeDlg", "Enter a date and time"))
        self.timeEdit.setDisplayFormat(_translate("timeDlg", "hh:mm:ss"))
        self.pbGetCurrentTime.setText(_translate("timeDlg", "Get Current Time"))
        self.cancelBtn.setText(_translate("timeDlg", "Cancel"))
        self.okBtn.setText(_translate("timeDlg", "OK"))
