# Form implementation generated from reading ui file 'C:\Users\Melina.Shak\Documents\CLAMS\ui\TypeSelDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_typeselDialog(object):
    def setupUi(self, typeselDialog):
        typeselDialog.setObjectName("typeselDialog")
        typeselDialog.resize(288, 237)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(typeselDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=typeselDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_0 = QtWidgets.QPushButton(parent=typeselDialog)
        self.btn_0.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_0.setFont(font)
        self.btn_0.setText("")
        self.btn_0.setObjectName("btn_0")
        self.verticalLayout.addWidget(self.btn_0)
        self.btn_1 = QtWidgets.QPushButton(parent=typeselDialog)
        self.btn_1.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_1.setFont(font)
        self.btn_1.setText("")
        self.btn_1.setObjectName("btn_1")
        self.verticalLayout.addWidget(self.btn_1)
        self.btn_2 = QtWidgets.QPushButton(parent=typeselDialog)
        self.btn_2.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_2.setFont(font)
        self.btn_2.setText("")
        self.btn_2.setObjectName("btn_2")
        self.verticalLayout.addWidget(self.btn_2)
        self.btn_3 = QtWidgets.QPushButton(parent=typeselDialog)
        self.btn_3.setMinimumSize(QtCore.QSize(165, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_3.setFont(font)
        self.btn_3.setText("")
        self.btn_3.setObjectName("btn_3")
        self.verticalLayout.addWidget(self.btn_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(typeselDialog)
        QtCore.QMetaObject.connectSlotsByName(typeselDialog)

    def retranslateUi(self, typeselDialog):
        _translate = QtCore.QCoreApplication.translate
        typeselDialog.setWindowTitle(_translate("typeselDialog", "Sample Type"))
        self.label.setText(_translate("typeselDialog", "Basket Sample Type?"))
