# Form implementation generated from reading ui file 'C:\Users\rick.towler\Work\noaa-afsc-mace\CLAMS\ui\UtilitiesDlg.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_utilitiesdlg(object):
    def setupUi(self, utilitiesdlg):
        utilitiesdlg.setObjectName("utilitiesdlg")
        utilitiesdlg.resize(400, 359)
        self.verticalLayout = QtWidgets.QVBoxLayout(utilitiesdlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=utilitiesdlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.setupBtn = QtWidgets.QPushButton(parent=utilitiesdlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.setupBtn.setFont(font)
        self.setupBtn.setObjectName("setupBtn")
        self.verticalLayout.addWidget(self.setupBtn)
        self.loadStreamBtn = QtWidgets.QPushButton(parent=utilitiesdlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.loadStreamBtn.setFont(font)
        self.loadStreamBtn.setObjectName("loadStreamBtn")
        self.verticalLayout.addWidget(self.loadStreamBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.doneBtn = QtWidgets.QPushButton(parent=utilitiesdlg)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.doneBtn.setFont(font)
        self.doneBtn.setObjectName("doneBtn")
        self.verticalLayout.addWidget(self.doneBtn)

        self.retranslateUi(utilitiesdlg)
        QtCore.QMetaObject.connectSlotsByName(utilitiesdlg)

    def retranslateUi(self, utilitiesdlg):
        _translate = QtCore.QCoreApplication.translate
        utilitiesdlg.setWindowTitle(_translate("utilitiesdlg", "CLAMS Utilities"))
        self.label.setText(_translate("utilitiesdlg", "CLAMS Utilities"))
        self.setupBtn.setText(_translate("utilitiesdlg", "Setup Serial Devices"))
        self.loadStreamBtn.setText(_translate("utilitiesdlg", "load stream data"))
        self.doneBtn.setText(_translate("utilitiesdlg", "Done"))
